// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HotelRoomThermostat

#ifndef _HOTELROOMTHERMOSTAT_UI_H
#define _HOTELROOMTHERMOSTAT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Main.h"
#include "ui_PinEntry.h"
#include "ui_Settings1.h"
#include "ui_Settings2.h"
#include "ui_Settings3.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_dnd_png);    // assets/dnd.png
LV_IMG_DECLARE(ui_img_mur_png);    // assets/mur.png
LV_IMG_DECLARE(ui_img_hvac_png);    // assets/hvac.png
LV_IMG_DECLARE(ui_img_thermo_inc_png);    // assets/thermo_inc.png
LV_IMG_DECLARE(ui_img_fan_mode_png);    // assets/fan_mode.png
LV_IMG_DECLARE(ui_img_thermo_dec_png);    // assets/thermo_dec.png
LV_IMG_DECLARE(ui_img_heating_png);    // assets/heating.png
LV_IMG_DECLARE(ui_img_cooling_png);    // assets/cooling.png
LV_IMG_DECLARE(ui_img_sunny_png);    // assets/sunny.png
LV_IMG_DECLARE(ui_img_sunny_day_png);    // assets/sunny_day.png

// FONTS
LV_FONT_DECLARE(ui_font_fontinterlight80);

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_relocalize(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
