// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HotelRoomThermostat

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void action_dnd_toggled(lv_event_t * e);
void action_mur_toggled(lv_event_t * e);
void action_go_to_thermo(lv_event_t * e);
void action_temp_inc(lv_event_t * e);
void action_fan_speed_change(lv_event_t * e);
void action_temp_dec(lv_event_t * e);
void action_clean_start(lv_event_t * e);
void action_validate_pin(lv_event_t * e);
void action_min_temp_changed(lv_event_t * e);
void action_max_temp_changed(lv_event_t * e);
void action_hvac_mode_changed(lv_event_t * e);
void action_ctrl_type_changed(lv_event_t * e);
void action_save_and_exit(lv_event_t * e);
void action_hysteresis_changed(lv_event_t * e);
void action_stage_step_changed(lv_event_t * e);
void action_offset_changed(lv_event_t * e);
void settings3_loaded_cb(lv_event_t * e);
void action_bright_high_changed(lv_event_t * e);
void action_bright_low_changed(lv_event_t * e);
void action_timeout_changed(lv_event_t * e);
void action_modbus_changed(lv_event_t * e);
void action_start_wifi_manager(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
