// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HotelRoomThermostat

#include "ui.h"

lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_SwipeContainer = NULL;
lv_obj_t * ui_TileMain = NULL;
lv_obj_t * ui_LabelClock = NULL;
lv_obj_t * ui_LabelCurrentTemp = NULL;
lv_obj_t * ui_LabelOutdoorTemp = NULL;
lv_obj_t * ui_ImageWeatherIcon = NULL;
lv_obj_t * ui_ButtonDnd = NULL;
lv_obj_t * ui_LabelDnd = NULL;
lv_obj_t * ui_ButtonMur = NULL;
lv_obj_t * ui_LabelMur = NULL;
lv_obj_t * ui_ButtonGoToThermostat = NULL;
lv_obj_t * ui_LabelTermostat = NULL;
lv_obj_t * ui_ButtonHiddenMenu = NULL;
lv_obj_t * ui_TileThermostat = NULL;
lv_obj_t * ui_LabelTargetTemp = NULL;
lv_obj_t * ui_ArcTemp = NULL;
lv_obj_t * ui_BtnTempInc = NULL;
lv_obj_t * ui_BtnFan = NULL;
lv_obj_t * ui_LabelFanStatus = NULL;
lv_obj_t * ui_BtnTempDec = NULL;
lv_obj_t * ui_LabelRoomTemp = NULL;
lv_obj_t * ui_ImageHeatStatus = NULL;
lv_obj_t * ui_ImageCoolStatus = NULL;
lv_obj_t * ui_TileWeather = NULL;
lv_obj_t * ui_LabelWeatherCity = NULL;
lv_obj_t * ui_LabelWeatherTodayTemp = NULL;
lv_obj_t * ui_ImageWeatherTodayIcon = NULL;
lv_obj_t * ui_ContainerForecast = NULL;
lv_obj_t * ui_CardDay1 = NULL;
lv_obj_t * ui_LabelDay1 = NULL;
lv_obj_t * ui_ImgIcon1 = NULL;
lv_obj_t * ui_LabelTempHigh1 = NULL;
lv_obj_t * ui_LabelTempLow1 = NULL;
lv_obj_t * ui_CardDay2 = NULL;
lv_obj_t * ui_LabelDay2 = NULL;
lv_obj_t * ui_ImgIcon2 = NULL;
lv_obj_t * ui_LabelTempHigh2 = NULL;
lv_obj_t * ui_LabelTempLow2 = NULL;
lv_obj_t * ui_CardDay3 = NULL;
lv_obj_t * ui_LabelDay3 = NULL;
lv_obj_t * ui_ImgIcon3 = NULL;
lv_obj_t * ui_LabelTempHigh3 = NULL;
lv_obj_t * ui_LabelTempLow3 = NULL;
lv_obj_t * ui_CardDay4 = NULL;
lv_obj_t * ui_LabelDay4 = NULL;
lv_obj_t * ui_ImgIcon4 = NULL;
lv_obj_t * ui_LabelTempHigh4 = NULL;
lv_obj_t * ui_LabelTempLow4 = NULL;
lv_obj_t * ui_CardDay5 = NULL;
lv_obj_t * ui_LabelDay5 = NULL;
lv_obj_t * ui_ImgIcon5 = NULL;
lv_obj_t * ui_LabelTempHigh5 = NULL;
lv_obj_t * ui_LabelTempLow5 = NULL;
lv_obj_t * ui_ImageWeatherTodayIcon1 = NULL;
lv_obj_t * ui_ImageWeatherTodayIcon2 = NULL;
lv_obj_t * ui_ImageWeatherTodayIcon3 = NULL;
lv_obj_t * ui_ImageWeatherTodayIcon4 = NULL;
lv_obj_t * ui_ImageWeatherTodayIcon5 = NULL;
lv_obj_t * ui_ImageWeatherTodayIcon6 = NULL;
lv_obj_t * ui_ImageAsset1 = NULL;
lv_obj_t * ui_ImageAsset2 = NULL;
lv_obj_t * ui_ImageAsset3 = NULL;
lv_obj_t * ui_ImageAsset4 = NULL;
lv_obj_t * ui_ImageWeatherTodayIcon7 = NULL;
lv_obj_t * ui_TileClean = NULL;
lv_obj_t * ui_BtnCleanStart = NULL;
lv_obj_t * ui_LabelCleanText = NULL;
lv_obj_t * ui_LabelCleanCountdown = NULL;
// event funtions
void ui_event_ButtonDnd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        action_dnd_toggled(e);
    }
}

void ui_event_ButtonMur(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        action_mur_toggled(e);
    }
}

void ui_event_ButtonGoToThermostat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        action_go_to_thermo(e);
    }
}

void ui_event_ButtonHiddenMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_PinEntry, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_PinEntry_screen_init);
    }
}

void ui_event_BtnTempInc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        action_temp_inc(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        action_temp_inc(e);
    }
}

void ui_event_BtnFan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        action_fan_speed_change(e);
    }
}

void ui_event_BtnTempDec(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        action_temp_dec(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        action_temp_dec(e);
    }
}

void ui_event_BtnCleanStart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        action_clean_start(e);
    }
}

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwipeContainer = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_SwipeContainer, lv_pct(100));
    lv_obj_set_height(ui_SwipeContainer, lv_pct(100));
    lv_obj_set_align(ui_SwipeContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SwipeContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SwipeContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_SwipeContainer, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_scroll_dir(ui_SwipeContainer, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_SwipeContainer, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_SwipeContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwipeContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TileMain = lv_obj_create(ui_SwipeContainer);
    lv_obj_set_width(ui_TileMain, lv_pct(100));
    lv_obj_set_height(ui_TileMain, lv_pct(100));
    lv_obj_set_x(ui_TileMain, -9);
    lv_obj_set_y(ui_TileMain, -23);
    lv_obj_set_align(ui_TileMain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TileMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TileMain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TileMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TileMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TileMain, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_TileMain, 210, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_TileMain, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_TileMain, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelClock = lv_label_create(ui_TileMain);
    lv_obj_set_width(ui_LabelClock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelClock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelClock, -10);
    lv_obj_set_y(ui_LabelClock, -60);
    lv_obj_set_align(ui_LabelClock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelClock, "12:00");
    lv_obj_set_style_text_color(ui_LabelClock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelClock, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelClock, &ui_font_fontinterlight80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCurrentTemp = lv_label_create(ui_TileMain);
    lv_obj_set_width(ui_LabelCurrentTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCurrentTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCurrentTemp, 120);
    lv_obj_set_y(ui_LabelCurrentTemp, 0);
    lv_obj_set_align(ui_LabelCurrentTemp, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelCurrentTemp, "Innen:    24°C");
    lv_obj_set_style_text_color(ui_LabelCurrentTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCurrentTemp, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCurrentTemp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOutdoorTemp = lv_label_create(ui_TileMain);
    lv_obj_set_width(ui_LabelOutdoorTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOutdoorTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOutdoorTemp, 120);
    lv_obj_set_y(ui_LabelOutdoorTemp, 30);
    lv_obj_set_align(ui_LabelOutdoorTemp, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelOutdoorTemp, "Aussen:  18°C");
    lv_obj_set_style_text_color(ui_LabelOutdoorTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOutdoorTemp, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOutdoorTemp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWeatherIcon = lv_img_create(ui_TileMain);
    lv_obj_set_width(ui_ImageWeatherIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWeatherIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWeatherIcon, 159);
    lv_obj_set_y(ui_ImageWeatherIcon, -188);
    lv_obj_set_align(ui_ImageWeatherIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWeatherIcon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWeatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonDnd = lv_btn_create(ui_TileMain);
    lv_obj_set_width(ui_ButtonDnd, 100);
    lv_obj_set_height(ui_ButtonDnd, 100);
    lv_obj_set_x(ui_ButtonDnd, 0);
    lv_obj_set_y(ui_ButtonDnd, -10);
    lv_obj_set_align(ui_ButtonDnd, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_ButtonDnd, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonDnd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonDnd, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonDnd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonDnd, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonDnd, &ui_img_dnd_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ButtonDnd, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonDnd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonDnd, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonDnd, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonDnd, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ButtonDnd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonDnd, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonDnd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonDnd, 30, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_ButtonDnd, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_ButtonDnd, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_ButtonDnd, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_ButtonDnd, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_ButtonDnd, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_ButtonDnd, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_ButtonDnd, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_ButtonDnd, 210, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelDnd = lv_label_create(ui_ButtonDnd);
    lv_obj_set_x(ui_LabelDnd, 0);
    lv_obj_set_y(ui_LabelDnd, 37);
    lv_obj_set_align(ui_LabelDnd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDnd, "DND");
    lv_obj_set_style_text_font(ui_LabelDnd, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelDnd, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_LabelDnd, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ButtonMur = lv_btn_create(ui_TileMain);
    lv_obj_set_width(ui_ButtonMur, 100);
    lv_obj_set_height(ui_ButtonMur, 100);
    lv_obj_set_x(ui_ButtonMur, 0);
    lv_obj_set_y(ui_ButtonMur, -10);
    lv_obj_set_align(ui_ButtonMur, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ButtonMur, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonMur, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMur, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMur, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMur, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonMur, &ui_img_mur_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ButtonMur, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonMur, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonMur, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonMur, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonMur, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ButtonMur, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonMur, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMur, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonMur, 30, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_ButtonMur, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_ButtonMur, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_ButtonMur, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_ButtonMur, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_ButtonMur, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_ButtonMur, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_ButtonMur, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_ButtonMur, 210, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelMur = lv_label_create(ui_ButtonMur);
    lv_obj_set_x(ui_LabelMur, 0);
    lv_obj_set_y(ui_LabelMur, 37);
    lv_obj_set_align(ui_LabelMur, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMur, "MUR");
    lv_obj_set_style_text_font(ui_LabelMur, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGoToThermostat = lv_btn_create(ui_TileMain);
    lv_obj_set_width(ui_ButtonGoToThermostat, 100);
    lv_obj_set_height(ui_ButtonGoToThermostat, 100);
    lv_obj_set_x(ui_ButtonGoToThermostat, 0);
    lv_obj_set_y(ui_ButtonGoToThermostat, -10);
    lv_obj_set_align(ui_ButtonGoToThermostat, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_ButtonGoToThermostat, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonGoToThermostat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonGoToThermostat, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonGoToThermostat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonGoToThermostat, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonGoToThermostat, &ui_img_hvac_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ButtonGoToThermostat, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonGoToThermostat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonGoToThermostat, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonGoToThermostat, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonGoToThermostat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonGoToThermostat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonGoToThermostat, 30, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_ButtonGoToThermostat, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_ButtonGoToThermostat, 210, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_ButtonGoToThermostat, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_ButtonGoToThermostat, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_ButtonGoToThermostat, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_ButtonGoToThermostat, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_ButtonGoToThermostat, lv_color_hex(0xFFFF07), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_ButtonGoToThermostat, 210, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelTermostat = lv_label_create(ui_ButtonGoToThermostat);
    lv_obj_set_x(ui_LabelTermostat, 0);
    lv_obj_set_y(ui_LabelTermostat, 37);
    lv_obj_set_align(ui_LabelTermostat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTermostat, "TERMO");
    lv_obj_set_style_text_font(ui_LabelTermostat, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonHiddenMenu = lv_btn_create(ui_TileMain);
    lv_obj_set_width(ui_ButtonHiddenMenu, 50);
    lv_obj_set_height(ui_ButtonHiddenMenu, 50);
    lv_obj_add_flag(ui_ButtonHiddenMenu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonHiddenMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonHiddenMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonHiddenMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TileThermostat = lv_obj_create(ui_SwipeContainer);
    lv_obj_set_width(ui_TileThermostat, lv_pct(100));
    lv_obj_set_height(ui_TileThermostat, lv_pct(100));
    lv_obj_set_align(ui_TileThermostat, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TileThermostat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TileThermostat, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TileThermostat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TileThermostat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTargetTemp = lv_label_create(ui_TileThermostat);
    lv_obj_set_width(ui_LabelTargetTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTargetTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTargetTemp, 7);
    lv_obj_set_y(ui_LabelTargetTemp, -40);
    lv_obj_set_align(ui_LabelTargetTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTargetTemp, "22°");
    lv_obj_set_style_text_color(ui_LabelTargetTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTargetTemp, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTargetTemp, &ui_font_fontinterlight80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcTemp = lv_arc_create(ui_TileThermostat);
    lv_obj_set_width(ui_ArcTemp, 300);
    lv_obj_set_height(ui_ArcTemp, 300);
    lv_obj_set_x(ui_ArcTemp, 0);
    lv_obj_set_y(ui_ArcTemp, -40);
    lv_obj_set_align(ui_ArcTemp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcTemp, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_ArcTemp, 10, 40);
    lv_arc_set_value(ui_ArcTemp, 22);
    lv_arc_set_bg_angles(ui_ArcTemp, 135, 45);
    lv_obj_set_style_arc_color(ui_ArcTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemp, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcTemp, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcTemp, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcTemp, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcTemp, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcTemp, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcTemp, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BtnTempInc = lv_btn_create(ui_TileThermostat);
    lv_obj_set_width(ui_BtnTempInc, 100);
    lv_obj_set_height(ui_BtnTempInc, 100);
    lv_obj_set_x(ui_BtnTempInc, 0);
    lv_obj_set_y(ui_BtnTempInc, -10);
    lv_obj_set_align(ui_BtnTempInc, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_BtnTempInc, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnTempInc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnTempInc, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnTempInc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnTempInc, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnTempInc, &ui_img_thermo_inc_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_BtnTempInc, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnTempInc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnTempInc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnTempInc, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnTempInc, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnTempInc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnTempInc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BtnTempInc, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_BtnTempInc, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BtnTempInc, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BtnTempInc, 35, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BtnTempInc, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_BtnFan = lv_btn_create(ui_TileThermostat);
    lv_obj_set_width(ui_BtnFan, 100);
    lv_obj_set_height(ui_BtnFan, 100);
    lv_obj_set_x(ui_BtnFan, 0);
    lv_obj_set_y(ui_BtnFan, -10);
    lv_obj_set_align(ui_BtnFan, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_BtnFan, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnFan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnFan, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnFan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnFan, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnFan, &ui_img_fan_mode_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_BtnFan, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnFan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnFan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnFan, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnFan, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnFan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnFan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BtnFan, 35, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_BtnFan, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BtnFan, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BtnFan, 35, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BtnFan, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelFanStatus = lv_label_create(ui_BtnFan);
    lv_obj_set_width(ui_LabelFanStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFanStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFanStatus, 0);
    lv_obj_set_y(ui_LabelFanStatus, 35);
    lv_obj_set_align(ui_LabelFanStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFanStatus, "Auto");
    lv_obj_set_style_text_color(ui_LabelFanStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFanStatus, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelFanStatus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFanStatus, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnTempDec = lv_btn_create(ui_TileThermostat);
    lv_obj_set_width(ui_BtnTempDec, 100);
    lv_obj_set_height(ui_BtnTempDec, 100);
    lv_obj_set_x(ui_BtnTempDec, 0);
    lv_obj_set_y(ui_BtnTempDec, -10);
    lv_obj_set_align(ui_BtnTempDec, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BtnTempDec, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnTempDec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnTempDec, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnTempDec, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnTempDec, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnTempDec, &ui_img_thermo_dec_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_BtnTempDec, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnTempDec, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnTempDec, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnTempDec, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnTempDec, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnTempDec, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnTempDec, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BtnTempDec, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_BtnTempDec, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BtnTempDec, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BtnTempDec, 35, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BtnTempDec, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelRoomTemp = lv_label_create(ui_TileThermostat);
    lv_obj_set_width(ui_LabelRoomTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRoomTemp, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelRoomTemp, "Innen: \n24°C");
    lv_obj_set_style_text_color(ui_LabelRoomTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelRoomTemp, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelRoomTemp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageHeatStatus = lv_img_create(ui_TileThermostat);
    lv_img_set_src(ui_ImageHeatStatus, &ui_img_heating_png);
    lv_obj_set_width(ui_ImageHeatStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageHeatStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageHeatStatus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageHeatStatus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHeatStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImageHeatStatus, lv_color_hex(0xFF9800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageHeatStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageCoolStatus = lv_img_create(ui_TileThermostat);
    lv_img_set_src(ui_ImageCoolStatus, &ui_img_cooling_png);
    lv_obj_set_width(ui_ImageCoolStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCoolStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageCoolStatus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageCoolStatus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCoolStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImageCoolStatus, lv_color_hex(0x00BFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageCoolStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TileWeather = lv_obj_create(ui_SwipeContainer);
    lv_obj_set_width(ui_TileWeather, lv_pct(100));
    lv_obj_set_height(ui_TileWeather, lv_pct(100));
    lv_obj_set_align(ui_TileWeather, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TileWeather, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TileWeather, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TileWeather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TileWeather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TileWeather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_TileWeather, 35, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelWeatherCity = lv_label_create(ui_TileWeather);
    lv_obj_set_width(ui_LabelWeatherCity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeatherCity, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelWeatherCity, "Sarajevo Today");
    lv_obj_set_style_text_font(ui_LabelWeatherCity, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWeatherTodayTemp = lv_label_create(ui_TileWeather);
    lv_obj_set_width(ui_LabelWeatherTodayTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeatherTodayTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeatherTodayTemp, 0);
    lv_obj_set_y(ui_LabelWeatherTodayTemp, 30);
    lv_label_set_text(ui_LabelWeatherTodayTemp, "+1°C");
    lv_obj_set_style_text_font(ui_LabelWeatherTodayTemp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWeatherTodayIcon = lv_img_create(ui_TileWeather);
    lv_img_set_src(ui_ImageWeatherTodayIcon, &ui_img_partly_cloudy_day_128_png);
    lv_obj_set_width(ui_ImageWeatherTodayIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWeatherTodayIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageWeatherTodayIcon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageWeatherTodayIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWeatherTodayIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerForecast = lv_obj_create(ui_TileWeather);
    lv_obj_set_width(ui_ContainerForecast, lv_pct(100));
    lv_obj_set_height(ui_ContainerForecast, lv_pct(60));
    lv_obj_set_x(ui_ContainerForecast, 0);
    lv_obj_set_y(ui_ContainerForecast, -20);
    lv_obj_set_align(ui_ContainerForecast, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_ContainerForecast, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerForecast, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerForecast, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerForecast, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerForecast, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerForecast, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CardDay1 = lv_obj_create(ui_ContainerForecast);
    lv_obj_set_width(ui_CardDay1, lv_pct(18));
    lv_obj_set_height(ui_CardDay1, lv_pct(100));
    lv_obj_set_align(ui_CardDay1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CardDay1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CardDay1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CardDay1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CardDay1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDay1 = lv_label_create(ui_CardDay1);
    lv_obj_set_width(ui_LabelDay1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDay1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelDay1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelDay1, "PON");
    lv_obj_set_style_text_color(ui_LabelDay1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDay1, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDay1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgIcon1 = lv_img_create(ui_CardDay1);
    lv_img_set_src(ui_ImgIcon1, &ui_img_clear_night_png);
    lv_obj_set_width(ui_ImgIcon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgIcon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgIcon1, 0);
    lv_obj_set_y(ui_ImgIcon1, -25);
    lv_obj_set_align(ui_ImgIcon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgIcon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgIcon1, 150);

    ui_LabelTempHigh1 = lv_label_create(ui_CardDay1);
    lv_obj_set_width(ui_LabelTempHigh1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempHigh1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempHigh1, 0);
    lv_obj_set_y(ui_LabelTempHigh1, -45);
    lv_obj_set_align(ui_LabelTempHigh1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelTempHigh1, "15°");
    lv_obj_set_style_text_color(ui_LabelTempHigh1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempHigh1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempHigh1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTempLow1 = lv_label_create(ui_CardDay1);
    lv_obj_set_width(ui_LabelTempLow1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempLow1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTempLow1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelTempLow1, "8°");
    lv_obj_set_style_text_color(ui_LabelTempLow1, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempLow1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempLow1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CardDay2 = lv_obj_create(ui_ContainerForecast);
    lv_obj_set_width(ui_CardDay2, lv_pct(18));
    lv_obj_set_height(ui_CardDay2, lv_pct(100));
    lv_obj_set_align(ui_CardDay2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CardDay2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CardDay2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CardDay2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CardDay2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDay2 = lv_label_create(ui_CardDay2);
    lv_obj_set_width(ui_LabelDay2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDay2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelDay2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelDay2, "PON");
    lv_obj_set_style_text_color(ui_LabelDay2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDay2, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDay2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgIcon2 = lv_img_create(ui_CardDay2);
    lv_img_set_src(ui_ImgIcon2, &ui_img_cloudy_png);
    lv_obj_set_width(ui_ImgIcon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgIcon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgIcon2, 0);
    lv_obj_set_y(ui_ImgIcon2, -25);
    lv_obj_set_align(ui_ImgIcon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgIcon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgIcon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgIcon2, 150);

    ui_LabelTempHigh2 = lv_label_create(ui_CardDay2);
    lv_obj_set_width(ui_LabelTempHigh2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempHigh2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempHigh2, 0);
    lv_obj_set_y(ui_LabelTempHigh2, -45);
    lv_obj_set_align(ui_LabelTempHigh2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelTempHigh2, "15°");
    lv_obj_set_style_text_color(ui_LabelTempHigh2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempHigh2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempHigh2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTempLow2 = lv_label_create(ui_CardDay2);
    lv_obj_set_width(ui_LabelTempLow2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempLow2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTempLow2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelTempLow2, "8°");
    lv_obj_set_style_text_color(ui_LabelTempLow2, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempLow2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempLow2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CardDay3 = lv_obj_create(ui_ContainerForecast);
    lv_obj_set_width(ui_CardDay3, lv_pct(18));
    lv_obj_set_height(ui_CardDay3, lv_pct(100));
    lv_obj_set_align(ui_CardDay3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CardDay3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CardDay3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CardDay3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CardDay3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDay3 = lv_label_create(ui_CardDay3);
    lv_obj_set_width(ui_LabelDay3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDay3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelDay3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelDay3, "PON");
    lv_obj_set_style_text_color(ui_LabelDay3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDay3, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDay3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgIcon3 = lv_img_create(ui_CardDay3);
    lv_img_set_src(ui_ImgIcon3, &ui_img_foggy_png);
    lv_obj_set_width(ui_ImgIcon3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgIcon3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgIcon3, 0);
    lv_obj_set_y(ui_ImgIcon3, -25);
    lv_obj_set_align(ui_ImgIcon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgIcon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgIcon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgIcon3, 150);

    ui_LabelTempHigh3 = lv_label_create(ui_CardDay3);
    lv_obj_set_width(ui_LabelTempHigh3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempHigh3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempHigh3, 0);
    lv_obj_set_y(ui_LabelTempHigh3, -45);
    lv_obj_set_align(ui_LabelTempHigh3, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelTempHigh3, "15°");
    lv_obj_set_style_text_color(ui_LabelTempHigh3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempHigh3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempHigh3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTempLow3 = lv_label_create(ui_CardDay3);
    lv_obj_set_width(ui_LabelTempLow3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempLow3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTempLow3, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelTempLow3, "8°");
    lv_obj_set_style_text_color(ui_LabelTempLow3, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempLow3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempLow3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CardDay4 = lv_obj_create(ui_ContainerForecast);
    lv_obj_set_width(ui_CardDay4, lv_pct(18));
    lv_obj_set_height(ui_CardDay4, lv_pct(100));
    lv_obj_set_align(ui_CardDay4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CardDay4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CardDay4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CardDay4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CardDay4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDay4 = lv_label_create(ui_CardDay4);
    lv_obj_set_width(ui_LabelDay4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDay4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelDay4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelDay4, "PON");
    lv_obj_set_style_text_color(ui_LabelDay4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDay4, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDay4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgIcon4 = lv_img_create(ui_CardDay4);
    lv_img_set_src(ui_ImgIcon4, &ui_img_partly_cloudy_day_png);
    lv_obj_set_width(ui_ImgIcon4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgIcon4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgIcon4, 0);
    lv_obj_set_y(ui_ImgIcon4, -25);
    lv_obj_set_align(ui_ImgIcon4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgIcon4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgIcon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgIcon4, 150);

    ui_LabelTempHigh4 = lv_label_create(ui_CardDay4);
    lv_obj_set_width(ui_LabelTempHigh4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempHigh4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempHigh4, 0);
    lv_obj_set_y(ui_LabelTempHigh4, -45);
    lv_obj_set_align(ui_LabelTempHigh4, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelTempHigh4, "15°");
    lv_obj_set_style_text_color(ui_LabelTempHigh4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempHigh4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempHigh4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTempLow4 = lv_label_create(ui_CardDay4);
    lv_obj_set_width(ui_LabelTempLow4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempLow4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTempLow4, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelTempLow4, "8°");
    lv_obj_set_style_text_color(ui_LabelTempLow4, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempLow4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempLow4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CardDay5 = lv_obj_create(ui_ContainerForecast);
    lv_obj_set_width(ui_CardDay5, lv_pct(18));
    lv_obj_set_height(ui_CardDay5, lv_pct(100));
    lv_obj_set_align(ui_CardDay5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CardDay5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CardDay5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CardDay5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CardDay5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDay5 = lv_label_create(ui_CardDay5);
    lv_obj_set_width(ui_LabelDay5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDay5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelDay5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelDay5, "PON");
    lv_obj_set_style_text_color(ui_LabelDay5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDay5, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDay5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgIcon5 = lv_img_create(ui_CardDay5);
    lv_img_set_src(ui_ImgIcon5, &ui_img_partly_cloudy_night_png);
    lv_obj_set_width(ui_ImgIcon5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgIcon5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgIcon5, 0);
    lv_obj_set_y(ui_ImgIcon5, -25);
    lv_obj_set_align(ui_ImgIcon5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgIcon5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgIcon5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgIcon5, 150);

    ui_LabelTempHigh5 = lv_label_create(ui_CardDay5);
    lv_obj_set_width(ui_LabelTempHigh5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempHigh5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempHigh5, 0);
    lv_obj_set_y(ui_LabelTempHigh5, -45);
    lv_obj_set_align(ui_LabelTempHigh5, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelTempHigh5, "15°");
    lv_obj_set_style_text_color(ui_LabelTempHigh5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempHigh5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempHigh5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTempLow5 = lv_label_create(ui_CardDay5);
    lv_obj_set_width(ui_LabelTempLow5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempLow5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTempLow5, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelTempLow5, "8°");
    lv_obj_set_style_text_color(ui_LabelTempLow5, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempLow5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempLow5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWeatherTodayIcon1 = lv_img_create(ui_TileWeather);
    lv_img_set_src(ui_ImageWeatherTodayIcon1, &ui_img_rainy_128_png);
    lv_obj_set_width(ui_ImageWeatherTodayIcon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWeatherTodayIcon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageWeatherTodayIcon1, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageWeatherTodayIcon1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWeatherTodayIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWeatherTodayIcon2 = lv_img_create(ui_TileWeather);
    lv_img_set_src(ui_ImageWeatherTodayIcon2, &ui_img_partly_cloudy_night_128_png);
    lv_obj_set_width(ui_ImageWeatherTodayIcon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWeatherTodayIcon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageWeatherTodayIcon2, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageWeatherTodayIcon2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWeatherTodayIcon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWeatherTodayIcon3 = lv_img_create(ui_TileWeather);
    lv_img_set_src(ui_ImageWeatherTodayIcon3, &ui_img_storm_128_png);
    lv_obj_set_width(ui_ImageWeatherTodayIcon3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWeatherTodayIcon3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageWeatherTodayIcon3, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageWeatherTodayIcon3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWeatherTodayIcon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWeatherTodayIcon4 = lv_img_create(ui_TileWeather);
    lv_img_set_src(ui_ImageWeatherTodayIcon4, &ui_img_sunny_128_png);
    lv_obj_set_width(ui_ImageWeatherTodayIcon4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWeatherTodayIcon4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageWeatherTodayIcon4, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageWeatherTodayIcon4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWeatherTodayIcon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWeatherTodayIcon5 = lv_img_create(ui_TileWeather);
    lv_img_set_src(ui_ImageWeatherTodayIcon5, &ui_img_cloudy_128_png);
    lv_obj_set_width(ui_ImageWeatherTodayIcon5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWeatherTodayIcon5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageWeatherTodayIcon5, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageWeatherTodayIcon5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWeatherTodayIcon5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWeatherTodayIcon6 = lv_img_create(ui_TileWeather);
    lv_img_set_src(ui_ImageWeatherTodayIcon6, &ui_img_snowy_128_png);
    lv_obj_set_width(ui_ImageWeatherTodayIcon6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWeatherTodayIcon6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageWeatherTodayIcon6, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageWeatherTodayIcon6, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWeatherTodayIcon6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageAsset1 = lv_img_create(ui_TileWeather);
    lv_img_set_src(ui_ImageAsset1, &ui_img_rainy_png);
    lv_obj_set_width(ui_ImageAsset1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageAsset1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageAsset1, 0);
    lv_obj_set_y(ui_ImageAsset1, -200);
    lv_obj_set_align(ui_ImageAsset1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageAsset1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageAsset1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageAsset2 = lv_img_create(ui_TileWeather);
    lv_img_set_src(ui_ImageAsset2, &ui_img_snowy_png);
    lv_obj_set_width(ui_ImageAsset2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageAsset2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageAsset2, 0);
    lv_obj_set_y(ui_ImageAsset2, -200);
    lv_obj_set_align(ui_ImageAsset2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageAsset2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageAsset2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageAsset3 = lv_img_create(ui_TileWeather);
    lv_img_set_src(ui_ImageAsset3, &ui_img_storm_png);
    lv_obj_set_width(ui_ImageAsset3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageAsset3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageAsset3, 0);
    lv_obj_set_y(ui_ImageAsset3, -200);
    lv_obj_set_align(ui_ImageAsset3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageAsset3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageAsset3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageAsset4 = lv_img_create(ui_TileWeather);
    lv_img_set_src(ui_ImageAsset4, &ui_img_sunny_day_png);
    lv_obj_set_width(ui_ImageAsset4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageAsset4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageAsset4, 0);
    lv_obj_set_y(ui_ImageAsset4, -200);
    lv_obj_set_align(ui_ImageAsset4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageAsset4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageAsset4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWeatherTodayIcon7 = lv_img_create(ui_TileWeather);
    lv_img_set_src(ui_ImageWeatherTodayIcon7, &ui_img_foggy_128_png);
    lv_obj_set_width(ui_ImageWeatherTodayIcon7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWeatherTodayIcon7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageWeatherTodayIcon7, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageWeatherTodayIcon7, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWeatherTodayIcon7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TileClean = lv_obj_create(ui_SwipeContainer);
    lv_obj_set_width(ui_TileClean, lv_pct(100));
    lv_obj_set_height(ui_TileClean, lv_pct(100));
    lv_obj_set_align(ui_TileClean, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TileClean, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TileClean, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TileClean, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TileClean, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCleanStart = lv_btn_create(ui_TileClean);
    lv_obj_set_width(ui_BtnCleanStart, 120);
    lv_obj_set_height(ui_BtnCleanStart, 80);
    lv_obj_set_x(ui_BtnCleanStart, 0);
    lv_obj_set_y(ui_BtnCleanStart, 80);
    lv_obj_set_align(ui_BtnCleanStart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCleanStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCleanStart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnCleanStart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnCleanStart, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnCleanStart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnCleanStart, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnCleanStart, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnCleanStart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnCleanStart, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BtnCleanStart, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BtnCleanStart, 35, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BtnCleanStart, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelCleanText = lv_label_create(ui_BtnCleanStart);
    lv_obj_set_width(ui_LabelCleanText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCleanText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelCleanText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCleanText, "CLEAN");
    lv_obj_set_style_text_font(ui_LabelCleanText, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCleanCountdown = lv_label_create(ui_TileClean);
    lv_obj_set_width(ui_LabelCleanCountdown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCleanCountdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCleanCountdown, 0);
    lv_obj_set_y(ui_LabelCleanCountdown, -50);
    lv_obj_set_align(ui_LabelCleanCountdown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCleanCountdown, "60");
    lv_obj_set_style_text_font(ui_LabelCleanCountdown, &ui_font_fontinterlight80, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonDnd, ui_event_ButtonDnd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonMur, ui_event_ButtonMur, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonGoToThermostat, ui_event_ButtonGoToThermostat, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonHiddenMenu, ui_event_ButtonHiddenMenu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnTempInc, ui_event_BtnTempInc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnFan, ui_event_BtnFan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnTempDec, ui_event_BtnTempDec, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnCleanStart, ui_event_BtnCleanStart, LV_EVENT_ALL, NULL);

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    ui_SwipeContainer = NULL;
    ui_TileMain = NULL;
    ui_LabelClock = NULL;
    ui_LabelCurrentTemp = NULL;
    ui_LabelOutdoorTemp = NULL;
    ui_ImageWeatherIcon = NULL;
    ui_ButtonDnd = NULL;
    ui_LabelDnd = NULL;
    ui_ButtonMur = NULL;
    ui_LabelMur = NULL;
    ui_ButtonGoToThermostat = NULL;
    ui_LabelTermostat = NULL;
    ui_ButtonHiddenMenu = NULL;
    ui_TileThermostat = NULL;
    ui_LabelTargetTemp = NULL;
    ui_ArcTemp = NULL;
    ui_BtnTempInc = NULL;
    ui_BtnFan = NULL;
    ui_LabelFanStatus = NULL;
    ui_BtnTempDec = NULL;
    ui_LabelRoomTemp = NULL;
    ui_ImageHeatStatus = NULL;
    ui_ImageCoolStatus = NULL;
    ui_TileWeather = NULL;
    ui_LabelWeatherCity = NULL;
    ui_LabelWeatherTodayTemp = NULL;
    ui_ImageWeatherTodayIcon = NULL;
    ui_ContainerForecast = NULL;
    ui_CardDay1 = NULL;
    ui_LabelDay1 = NULL;
    ui_ImgIcon1 = NULL;
    ui_LabelTempHigh1 = NULL;
    ui_LabelTempLow1 = NULL;
    ui_CardDay2 = NULL;
    ui_LabelDay2 = NULL;
    ui_ImgIcon2 = NULL;
    ui_LabelTempHigh2 = NULL;
    ui_LabelTempLow2 = NULL;
    ui_CardDay3 = NULL;
    ui_LabelDay3 = NULL;
    ui_ImgIcon3 = NULL;
    ui_LabelTempHigh3 = NULL;
    ui_LabelTempLow3 = NULL;
    ui_CardDay4 = NULL;
    ui_LabelDay4 = NULL;
    ui_ImgIcon4 = NULL;
    ui_LabelTempHigh4 = NULL;
    ui_LabelTempLow4 = NULL;
    ui_CardDay5 = NULL;
    ui_LabelDay5 = NULL;
    ui_ImgIcon5 = NULL;
    ui_LabelTempHigh5 = NULL;
    ui_LabelTempLow5 = NULL;
    ui_ImageWeatherTodayIcon1 = NULL;
    ui_ImageWeatherTodayIcon2 = NULL;
    ui_ImageWeatherTodayIcon3 = NULL;
    ui_ImageWeatherTodayIcon4 = NULL;
    ui_ImageWeatherTodayIcon5 = NULL;
    ui_ImageWeatherTodayIcon6 = NULL;
    ui_ImageAsset1 = NULL;
    ui_ImageAsset2 = NULL;
    ui_ImageAsset3 = NULL;
    ui_ImageAsset4 = NULL;
    ui_ImageWeatherTodayIcon7 = NULL;
    ui_TileClean = NULL;
    ui_BtnCleanStart = NULL;
    ui_LabelCleanText = NULL;
    ui_LabelCleanCountdown = NULL;

}

void ui_Main_screen_relocalize(void)
{
    // label widgets on screen

}
