// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HotelRoomThermostat

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern void ui_Main_screen_relocalize(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_SwipeContainer;
extern lv_obj_t * ui_TileMain;
extern lv_obj_t * ui_LabelClock;
extern lv_obj_t * ui_LabelCurrentTemp;
extern lv_obj_t * ui_LabelOutdoorTemp;
extern lv_obj_t * ui_ImageWeatherIcon;
extern void ui_event_ButtonDnd(lv_event_t * e);
extern lv_obj_t * ui_ButtonDnd;
extern lv_obj_t * ui_LabelDnd;
extern void ui_event_ButtonMur(lv_event_t * e);
extern lv_obj_t * ui_ButtonMur;
extern lv_obj_t * ui_LabelMur;
extern void ui_event_ButtonGoToThermostat(lv_event_t * e);
extern lv_obj_t * ui_ButtonGoToThermostat;
extern lv_obj_t * ui_LabelTermostat;
extern void ui_event_ButtonHiddenMenu(lv_event_t * e);
extern lv_obj_t * ui_ButtonHiddenMenu;
extern lv_obj_t * ui_TileThermostat;
extern lv_obj_t * ui_LabelTargetTemp;
extern lv_obj_t * ui_ArcTemp;
extern void ui_event_BtnTempInc(lv_event_t * e);
extern lv_obj_t * ui_BtnTempInc;
extern void ui_event_BtnFan(lv_event_t * e);
extern lv_obj_t * ui_BtnFan;
extern lv_obj_t * ui_LabelFanStatus;
extern void ui_event_BtnTempDec(lv_event_t * e);
extern lv_obj_t * ui_BtnTempDec;
extern lv_obj_t * ui_LabelRoomTemp;
extern lv_obj_t * ui_ImageHeatStatus;
extern lv_obj_t * ui_ImageCoolStatus;
extern lv_obj_t * ui_TileWeather;
extern lv_obj_t * ui_LabelWeatherCity;
extern lv_obj_t * ui_LabelWeatherTodayTemp;
extern lv_obj_t * ui_ImageWeatherTodayIcon;
extern lv_obj_t * ui_ContainerForecast;
extern lv_obj_t * ui_CardDay1;
extern lv_obj_t * ui_LabelDay1;
extern lv_obj_t * ui_ImgIcon1;
extern lv_obj_t * ui_LabelTempHigh1;
extern lv_obj_t * ui_LabelTempLow1;
extern lv_obj_t * ui_CardDay2;
extern lv_obj_t * ui_LabelDay2;
extern lv_obj_t * ui_ImgIcon2;
extern lv_obj_t * ui_LabelTempHigh2;
extern lv_obj_t * ui_LabelTempLow2;
extern lv_obj_t * ui_CardDay3;
extern lv_obj_t * ui_LabelDay3;
extern lv_obj_t * ui_ImgIcon3;
extern lv_obj_t * ui_LabelTempHigh3;
extern lv_obj_t * ui_LabelTempLow3;
extern lv_obj_t * ui_CardDay4;
extern lv_obj_t * ui_LabelDay4;
extern lv_obj_t * ui_ImgIcon4;
extern lv_obj_t * ui_LabelTempHigh4;
extern lv_obj_t * ui_LabelTempLow4;
extern lv_obj_t * ui_CardDay5;
extern lv_obj_t * ui_LabelDay5;
extern lv_obj_t * ui_ImgIcon5;
extern lv_obj_t * ui_LabelTempHigh5;
extern lv_obj_t * ui_LabelTempLow5;
extern lv_obj_t * ui_ImageWeatherTodayIcon1;
extern lv_obj_t * ui_ImageWeatherTodayIcon2;
extern lv_obj_t * ui_ImageWeatherTodayIcon3;
extern lv_obj_t * ui_ImageWeatherTodayIcon4;
extern lv_obj_t * ui_ImageWeatherTodayIcon5;
extern lv_obj_t * ui_ImageWeatherTodayIcon6;
extern lv_obj_t * ui_ImageAsset1;
extern lv_obj_t * ui_ImageAsset2;
extern lv_obj_t * ui_ImageAsset3;
extern lv_obj_t * ui_ImageAsset4;
extern lv_obj_t * ui_ImageWeatherTodayIcon7;
extern lv_obj_t * ui_LabelWeatherTodayDesc;
extern lv_obj_t * ui_TileClean;
extern void ui_event_BtnCleanStart(lv_event_t * e);
extern lv_obj_t * ui_BtnCleanStart;
extern lv_obj_t * ui_LabelCleanText;
extern lv_obj_t * ui_LabelCleanCountdown;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

