// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HotelRoomThermostat

#include "ui.h"

lv_obj_t * ui_Clean = NULL;
lv_obj_t * ui_TileClean2 = NULL;
lv_obj_t * ui_BtnCleanStart = NULL;
lv_obj_t * ui_LabelCleanText = NULL;
lv_obj_t * ui_BtnPrevClean = NULL;
lv_obj_t * ui_BtnNextClean = NULL;
lv_obj_t * ui_LabelCleanMsg = NULL;
lv_obj_t * ui_LabelCleanCountdown = NULL;
// event funtions
void ui_event_BtnCleanStart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        action_clean_pressed(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        action_clean_start(e);
    }
}

void ui_event_BtnPrevClean(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Thermostat, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Thermostat_screen_init);
    }
}

void ui_event_BtnNextClean(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Main_screen_init);
    }
}

// build funtions

void ui_Clean_screen_init(void)
{
    ui_Clean = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Clean, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Clean, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clean, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TileClean2 = lv_obj_create(ui_Clean);
    lv_obj_set_width(ui_TileClean2, lv_pct(100));
    lv_obj_set_height(ui_TileClean2, lv_pct(100));
    lv_obj_set_align(ui_TileClean2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TileClean2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TileClean2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TileClean2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TileClean2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCleanStart = lv_btn_create(ui_TileClean2);
    lv_obj_set_width(ui_BtnCleanStart, 100);
    lv_obj_set_height(ui_BtnCleanStart, 100);
    lv_obj_set_x(ui_BtnCleanStart, 0);
    lv_obj_set_y(ui_BtnCleanStart, -10);
    lv_obj_set_align(ui_BtnCleanStart, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_BtnCleanStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCleanStart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnCleanStart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnCleanStart, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnCleanStart, &ui_img_do_not_touch_48_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_BtnCleanStart, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnCleanStart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnCleanStart, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnCleanStart, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnCleanStart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnCleanStart, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BtnCleanStart, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BtnCleanStart, 35, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BtnCleanStart, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelCleanText = lv_label_create(ui_BtnCleanStart);
    lv_obj_set_width(ui_LabelCleanText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCleanText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCleanText, 4);
    lv_obj_set_y(ui_LabelCleanText, 35);
    lv_obj_set_align(ui_LabelCleanText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCleanText, "CLEAN");
    lv_obj_set_style_text_color(ui_LabelCleanText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCleanText, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCleanText, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPrevClean = lv_btn_create(ui_TileClean2);
    lv_obj_set_width(ui_BtnPrevClean, 100);
    lv_obj_set_height(ui_BtnPrevClean, 100);
    lv_obj_set_x(ui_BtnPrevClean, 0);
    lv_obj_set_y(ui_BtnPrevClean, -10);
    lv_obj_set_align(ui_BtnPrevClean, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BtnPrevClean, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPrevClean, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnPrevClean, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnPrevClean, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPrevClean, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnPrevClean, &ui_img_arrow_back_ios_48_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_BtnPrevClean, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnPrevClean, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnPrevClean, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnPrevClean, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnPrevClean, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnPrevClean, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnPrevClean, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BtnPrevClean, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_BtnPrevClean, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BtnPrevClean, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BtnPrevClean, 35, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BtnPrevClean, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_BtnNextClean = lv_btn_create(ui_TileClean2);
    lv_obj_set_width(ui_BtnNextClean, 100);
    lv_obj_set_height(ui_BtnNextClean, 100);
    lv_obj_set_x(ui_BtnNextClean, 0);
    lv_obj_set_y(ui_BtnNextClean, -10);
    lv_obj_set_align(ui_BtnNextClean, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_BtnNextClean, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNextClean, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNextClean, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnNextClean, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNextClean, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnNextClean, &ui_img_arrow_forward_ios_48_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_BtnNextClean, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnNextClean, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnNextClean, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnNextClean, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnNextClean, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnNextClean, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnNextClean, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BtnNextClean, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_BtnNextClean, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BtnNextClean, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BtnNextClean, 35, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BtnNextClean, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelCleanMsg = lv_label_create(ui_TileClean2);
    lv_obj_set_width(ui_LabelCleanMsg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCleanMsg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCleanMsg, 0);
    lv_obj_set_y(ui_LabelCleanMsg, -50);
    lv_obj_set_align(ui_LabelCleanMsg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCleanMsg,
                      "Reinigungsmodus:\n\nTippen Sie auf CLEAN,\num das Display \n60 Sekunden\n lang zu sperren.");
    lv_obj_set_style_text_align(ui_LabelCleanMsg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCleanMsg, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCleanCountdown = lv_label_create(ui_TileClean2);
    lv_obj_set_width(ui_LabelCleanCountdown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCleanCountdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCleanCountdown, 0);
    lv_obj_set_y(ui_LabelCleanCountdown, -50);
    lv_obj_set_align(ui_LabelCleanCountdown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCleanCountdown, "");
    lv_obj_set_style_text_font(ui_LabelCleanCountdown, &ui_font_fontinterlight80, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnCleanStart, ui_event_BtnCleanStart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnPrevClean, ui_event_BtnPrevClean, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNextClean, ui_event_BtnNextClean, LV_EVENT_ALL, NULL);

}

void ui_Clean_screen_destroy(void)
{
    if(ui_Clean) lv_obj_del(ui_Clean);

    // NULL screen variables
    ui_Clean = NULL;
    ui_TileClean2 = NULL;
    ui_BtnCleanStart = NULL;
    ui_LabelCleanText = NULL;
    ui_BtnPrevClean = NULL;
    ui_BtnNextClean = NULL;
    ui_LabelCleanMsg = NULL;
    ui_LabelCleanCountdown = NULL;

}

void ui_Clean_screen_relocalize(void)
{
    // label widgets on screen

}
