// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HotelRoomThermostat

#ifndef UI_CLEAN_H
#define UI_CLEAN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Clean
extern void ui_Clean_screen_init(void);
extern void ui_Clean_screen_destroy(void);
extern void ui_Clean_screen_relocalize(void);
extern lv_obj_t * ui_Clean;
extern lv_obj_t * ui_TileClean2;
extern void ui_event_BtnCleanStart(lv_event_t * e);
extern lv_obj_t * ui_BtnCleanStart;
extern lv_obj_t * ui_LabelCleanText;
extern void ui_event_BtnPrevClean(lv_event_t * e);
extern lv_obj_t * ui_BtnPrevClean;
extern void ui_event_BtnNextClean(lv_event_t * e);
extern lv_obj_t * ui_BtnNextClean;
extern lv_obj_t * ui_LabelCleanMsg;
extern lv_obj_t * ui_LabelCleanCountdown;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

