// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HotelRoomThermostat

#include "ui.h"

lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_TileMain = NULL;
lv_obj_t * ui_LabelClock = NULL;
lv_obj_t * ui_LabelCurrentTemp = NULL;
lv_obj_t * ui_LabelOutdoorTemp = NULL;
lv_obj_t * ui_ImageWeatherIcon = NULL;
lv_obj_t * ui_ButtonDnd = NULL;
lv_obj_t * ui_LabelDnd = NULL;
lv_obj_t * ui_ButtonMur = NULL;
lv_obj_t * ui_LabelMur = NULL;
lv_obj_t * ui_ButtonGoToThermostat = NULL;
lv_obj_t * ui_LabelTermostat = NULL;
lv_obj_t * ui_ButtonHiddenMenu = NULL;
// event funtions
void ui_event_ButtonDnd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        action_dnd_toggled(e);
    }
}

void ui_event_ButtonMur(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        action_mur_toggled(e);
    }
}

void ui_event_ButtonGoToThermostat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Thermostat, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Thermostat_screen_init);
    }
}

void ui_event_ButtonHiddenMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_PinEntry, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_PinEntry_screen_init);
    }
}

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TileMain = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_TileMain, lv_pct(100));
    lv_obj_set_height(ui_TileMain, lv_pct(100));
    lv_obj_set_align(ui_TileMain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TileMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TileMain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TileMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TileMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TileMain, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_TileMain, 210, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_TileMain, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_TileMain, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelClock = lv_label_create(ui_TileMain);
    lv_obj_set_width(ui_LabelClock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelClock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelClock, -10);
    lv_obj_set_y(ui_LabelClock, -60);
    lv_obj_set_align(ui_LabelClock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelClock, "12:00");
    lv_obj_set_style_text_color(ui_LabelClock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelClock, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelClock, &ui_font_fontinterlight80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCurrentTemp = lv_label_create(ui_TileMain);
    lv_obj_set_width(ui_LabelCurrentTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCurrentTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelCurrentTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCurrentTemp, "Innen:    24°C");
    lv_obj_set_style_text_color(ui_LabelCurrentTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCurrentTemp, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCurrentTemp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOutdoorTemp = lv_label_create(ui_TileMain);
    lv_obj_set_width(ui_LabelOutdoorTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOutdoorTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOutdoorTemp, 0);
    lv_obj_set_y(ui_LabelOutdoorTemp, 30);
    lv_obj_set_align(ui_LabelOutdoorTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOutdoorTemp, "Aussen:  18°C");
    lv_obj_set_style_text_color(ui_LabelOutdoorTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOutdoorTemp, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOutdoorTemp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWeatherIcon = lv_img_create(ui_TileMain);
    lv_obj_set_width(ui_ImageWeatherIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWeatherIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWeatherIcon, 159);
    lv_obj_set_y(ui_ImageWeatherIcon, -188);
    lv_obj_set_align(ui_ImageWeatherIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWeatherIcon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWeatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonDnd = lv_btn_create(ui_TileMain);
    lv_obj_set_width(ui_ButtonDnd, 100);
    lv_obj_set_height(ui_ButtonDnd, 100);
    lv_obj_set_x(ui_ButtonDnd, 0);
    lv_obj_set_y(ui_ButtonDnd, -10);
    lv_obj_set_align(ui_ButtonDnd, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_ButtonDnd, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonDnd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonDnd, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonDnd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonDnd, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonDnd, &ui_img_dnd_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ButtonDnd, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonDnd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonDnd, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonDnd, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonDnd, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ButtonDnd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonDnd, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonDnd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonDnd, 30, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_ButtonDnd, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_ButtonDnd, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_ButtonDnd, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_ButtonDnd, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_ButtonDnd, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_ButtonDnd, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_ButtonDnd, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_ButtonDnd, 210, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelDnd = lv_label_create(ui_ButtonDnd);
    lv_obj_set_x(ui_LabelDnd, 0);
    lv_obj_set_y(ui_LabelDnd, 37);
    lv_obj_set_align(ui_LabelDnd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDnd, "DND");
    lv_obj_set_style_text_font(ui_LabelDnd, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelDnd, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_LabelDnd, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ButtonMur = lv_btn_create(ui_TileMain);
    lv_obj_set_width(ui_ButtonMur, 100);
    lv_obj_set_height(ui_ButtonMur, 100);
    lv_obj_set_x(ui_ButtonMur, 0);
    lv_obj_set_y(ui_ButtonMur, -10);
    lv_obj_set_align(ui_ButtonMur, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ButtonMur, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonMur, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMur, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMur, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMur, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonMur, &ui_img_mur_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ButtonMur, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonMur, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonMur, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonMur, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonMur, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ButtonMur, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonMur, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMur, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonMur, 30, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_ButtonMur, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_ButtonMur, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_ButtonMur, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_ButtonMur, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_ButtonMur, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_ButtonMur, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_ButtonMur, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_ButtonMur, 210, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelMur = lv_label_create(ui_ButtonMur);
    lv_obj_set_x(ui_LabelMur, 0);
    lv_obj_set_y(ui_LabelMur, 37);
    lv_obj_set_align(ui_LabelMur, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMur, "MUR");
    lv_obj_set_style_text_font(ui_LabelMur, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGoToThermostat = lv_btn_create(ui_TileMain);
    lv_obj_set_width(ui_ButtonGoToThermostat, 100);
    lv_obj_set_height(ui_ButtonGoToThermostat, 100);
    lv_obj_set_x(ui_ButtonGoToThermostat, 0);
    lv_obj_set_y(ui_ButtonGoToThermostat, -10);
    lv_obj_set_align(ui_ButtonGoToThermostat, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_ButtonGoToThermostat, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonGoToThermostat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonGoToThermostat, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonGoToThermostat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonGoToThermostat, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonGoToThermostat, &ui_img_hvac_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ButtonGoToThermostat, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonGoToThermostat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonGoToThermostat, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonGoToThermostat, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonGoToThermostat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonGoToThermostat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonGoToThermostat, 30, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_ButtonGoToThermostat, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_ButtonGoToThermostat, 210, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_ButtonGoToThermostat, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_ButtonGoToThermostat, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_ButtonGoToThermostat, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_ButtonGoToThermostat, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_ButtonGoToThermostat, lv_color_hex(0xFFFF07), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_ButtonGoToThermostat, 210, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelTermostat = lv_label_create(ui_ButtonGoToThermostat);
    lv_obj_set_x(ui_LabelTermostat, 0);
    lv_obj_set_y(ui_LabelTermostat, 37);
    lv_obj_set_align(ui_LabelTermostat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTermostat, "KLIMA");
    lv_obj_set_style_text_color(ui_LabelTermostat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTermostat, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTermostat, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonHiddenMenu = lv_btn_create(ui_TileMain);
    lv_obj_set_width(ui_ButtonHiddenMenu, 50);
    lv_obj_set_height(ui_ButtonHiddenMenu, 50);
    lv_obj_add_flag(ui_ButtonHiddenMenu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonHiddenMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonHiddenMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonHiddenMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonDnd, ui_event_ButtonDnd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonMur, ui_event_ButtonMur, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonGoToThermostat, ui_event_ButtonGoToThermostat, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonHiddenMenu, ui_event_ButtonHiddenMenu, LV_EVENT_ALL, NULL);

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    ui_TileMain = NULL;
    ui_LabelClock = NULL;
    ui_LabelCurrentTemp = NULL;
    ui_LabelOutdoorTemp = NULL;
    ui_ImageWeatherIcon = NULL;
    ui_ButtonDnd = NULL;
    ui_LabelDnd = NULL;
    ui_ButtonMur = NULL;
    ui_LabelMur = NULL;
    ui_ButtonGoToThermostat = NULL;
    ui_LabelTermostat = NULL;
    ui_ButtonHiddenMenu = NULL;

}

void ui_Main_screen_relocalize(void)
{
    // label widgets on screen

}
