// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HotelRoomThermostat

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern void ui_Main_screen_relocalize(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_TileMain;
extern lv_obj_t * ui_LabelClock;
extern lv_obj_t * ui_LabelCurrentTemp;
extern lv_obj_t * ui_LabelOutdoorTemp;
extern lv_obj_t * ui_ImageWeatherIcon;
extern void ui_event_ButtonDnd(lv_event_t * e);
extern lv_obj_t * ui_ButtonDnd;
extern lv_obj_t * ui_LabelDnd;
extern void ui_event_ButtonMur(lv_event_t * e);
extern lv_obj_t * ui_ButtonMur;
extern lv_obj_t * ui_LabelMur;
extern void ui_event_ButtonGoToThermostat(lv_event_t * e);
extern lv_obj_t * ui_ButtonGoToThermostat;
extern lv_obj_t * ui_LabelTermostat;
extern void ui_event_ButtonHiddenMenu(lv_event_t * e);
extern lv_obj_t * ui_ButtonHiddenMenu;
// CUSTOM VARIABLES
extern lv_obj_t * ui_ContainerTempGrid;
extern lv_obj_t * ui_LabelCurrentVal;
extern lv_obj_t * ui_LabelOutdoorVal;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

