// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HotelRoomThermostat

#include "ui.h"

lv_obj_t * ui_PinEntry = NULL;
lv_obj_t * ui_PinTextArea = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
// event funtions
void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        action_validate_pin(e);
    }
}

// build funtions

void ui_PinEntry_screen_init(void)
{
    ui_PinEntry = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PinEntry, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PinEntry, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PinEntry, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PinEntry, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PinTextArea = lv_textarea_create(ui_PinEntry);
    lv_obj_set_width(ui_PinTextArea, 150);
    lv_obj_set_height(ui_PinTextArea, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_PinTextArea, 0);
    lv_obj_set_y(ui_PinTextArea, -140);
    lv_obj_set_align(ui_PinTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_PinTextArea, 5);
    lv_textarea_set_placeholder_text(ui_PinTextArea, "Placeholder...");
    lv_textarea_set_one_line(ui_PinTextArea, true);
    lv_textarea_set_password_mode(ui_PinTextArea, true);
    lv_obj_clear_flag(ui_PinTextArea, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_align(ui_PinTextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PinTextArea, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_PinEntry);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, lv_pct(90));
    lv_obj_set_height(ui_Keyboard1, lv_pct(50));
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 100);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    lv_keyboard_set_textarea(ui_Keyboard1, ui_PinTextArea);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);

}

void ui_PinEntry_screen_destroy(void)
{
    if(ui_PinEntry) lv_obj_del(ui_PinEntry);

    // NULL screen variables
    ui_PinEntry = NULL;
    ui_PinTextArea = NULL;
    ui_Keyboard1 = NULL;

}

void ui_PinEntry_screen_relocalize(void)
{
    // label widgets on screen

}
