// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HotelRoomThermostat

#ifndef UI_PINENTRY_H
#define UI_PINENTRY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PinEntry
extern void ui_PinEntry_screen_init(void);
extern void ui_PinEntry_screen_destroy(void);
extern void ui_PinEntry_screen_relocalize(void);
extern lv_obj_t * ui_PinEntry;
extern lv_obj_t * ui_PinTextArea;
extern void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

