// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HotelRoomThermostat

#ifndef UI_SETTINGS3_H
#define UI_SETTINGS3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings3
extern void ui_Settings3_screen_init(void);
extern void ui_Settings3_screen_destroy(void);
extern void ui_Settings3_screen_relocalize(void);
extern void ui_event_Settings3(lv_event_t * e);
extern lv_obj_t * ui_Settings3;
extern lv_obj_t * ui_LabelBrightHigh;
extern void ui_event_SliderBrightHigh(lv_event_t * e);
extern lv_obj_t * ui_SliderBrightHigh;
extern lv_obj_t * ui_LabelBrightLow;
extern void ui_event_SliderBrightLow(lv_event_t * e);
extern lv_obj_t * ui_SliderBrightLow;
extern lv_obj_t * ui_LabelTimeout;
extern void ui_event_DropTimeout(lv_event_t * e);
extern lv_obj_t * ui_DropTimeout;
extern lv_obj_t * ui_LabelModbus;
extern void ui_event_SpinModbusAddr(lv_event_t * e);
extern lv_obj_t * ui_SpinModbusAddr;
extern void ui_event_BtnModbusDec(lv_event_t * e);
extern lv_obj_t * ui_BtnModbusDec;
extern lv_obj_t * ui_LabelBtnModbusDec;
extern void ui_event_BtnModbusInc(lv_event_t * e);
extern lv_obj_t * ui_BtnModbusInc;
extern lv_obj_t * ui_LabelBtnModbusInc;
extern void ui_event_SwitchStartAp(lv_event_t * e);
extern lv_obj_t * ui_SwitchStartAp;
extern lv_obj_t * ui_LabelStartAp;
extern void ui_event_BtnSave3(lv_event_t * e);
extern lv_obj_t * ui_BtnSave3;
extern lv_obj_t * ui_LabelBtnSave3;
extern void ui_event_BtnNext3(lv_event_t * e);
extern lv_obj_t * ui_BtnNext3;
extern lv_obj_t * ui_LabelBtnNext3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

