// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HotelRoomThermostat

#ifndef UI_SETTINGS2_H
#define UI_SETTINGS2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings2
extern void ui_Settings2_screen_init(void);
extern void ui_Settings2_screen_destroy(void);
extern void ui_Settings2_screen_relocalize(void);
extern lv_obj_t * ui_Settings2;
extern void ui_event_Settings2(lv_event_t * e);
extern lv_obj_t * ui_LabelHysteresis;
extern void ui_event_DropHysteresis(lv_event_t * e);
extern lv_obj_t * ui_DropHysteresis;
extern lv_obj_t * ui_LabelStageStep;
extern void ui_event_DropStageStep(lv_event_t * e);
extern lv_obj_t * ui_DropStageStep;
extern lv_obj_t * ui_LabelSensorOffset;
extern void ui_event_SpinSensorOffset(lv_event_t * e);
extern lv_obj_t * ui_SpinSensorOffset;
extern void ui_event_BtnOffsetDec(lv_event_t * e);
extern lv_obj_t * ui_BtnOffsetDec;
extern lv_obj_t * ui_LabelBtnOffsetDec;
extern void ui_event_BtnOffsetInc(lv_event_t * e);
extern lv_obj_t * ui_BtnOffsetInc;
extern lv_obj_t * ui_LabelBtnOffsetInc;
extern void ui_event_BtnSave2(lv_event_t * e);
extern lv_obj_t * ui_BtnSave2;
extern lv_obj_t * ui_LabelBtnSave2;
extern void ui_event_BtnNext2(lv_event_t * e);
extern lv_obj_t * ui_BtnNext2;
extern lv_obj_t * ui_LabelBtnNext2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

