// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HotelRoomThermostat

#ifndef UI_SETTINGS1_H
#define UI_SETTINGS1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings1
extern void ui_Settings1_screen_init(void);
extern void ui_Settings1_screen_destroy(void);
extern void ui_Settings1_screen_relocalize(void);
extern lv_obj_t * ui_Settings1;
extern void ui_event_Settings1(lv_event_t * e);
extern lv_obj_t * ui_LabelMinTemp;
extern void ui_event_DropMinTemp(lv_event_t * e);
extern lv_obj_t * ui_DropMinTemp;
extern lv_obj_t * ui_LabelMaxTemp;
extern void ui_event_DropMaxTemp(lv_event_t * e);
extern lv_obj_t * ui_DropMaxTemp;
extern lv_obj_t * ui_LabelMode;
extern void ui_event_DropMode(lv_event_t * e);
extern lv_obj_t * ui_DropMode;
extern lv_obj_t * ui_LabelCtrlType;
extern void ui_event_DropCtrlType(lv_event_t * e);
extern lv_obj_t * ui_DropCtrlType;
extern void ui_event_BtnSave1(lv_event_t * e);
extern lv_obj_t * ui_BtnSave1;
extern lv_obj_t * ui_LabelBtnSave1;
extern void ui_event_BtnNext1(lv_event_t * e);
extern lv_obj_t * ui_BtnNext1;
extern lv_obj_t * ui_LabelBtnNext1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

